#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.5
#  in conjunction with Tcl version 8.6
#    Nov 08, 2020 03:45:04 PM -03  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import FirstApp_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = MainForm (root)
    FirstApp_support.init(root, top)
    root.mainloop()

w = None
def create_MainForm(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_MainForm(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = MainForm (w)
    FirstApp_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_MainForm():
    global w
    w.destroy()
    w = None

class MainForm:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+328+140")
        top.minsize(120, 1)
        top.maxsize(1284, 781)
        top.resizable(1,  1)
        top.title("My First Page App")
        top.configure(highlightcolor="black")

        self.btnExit = tk.Button(top)
        self.btnExit.place(relx=0.417, rely=0.422, height=24, width=97)
        self.btnExit.configure(activebackground="#d9d9d9")
        self.btnExit.configure(command=FirstApp_support.cmdExit)
        self.btnExit.configure(pady="0")
        self.btnExit.configure(text='''Exit''')

if __name__ == '__main__':
    vp_start_gui()





