#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.11f
# In conjunction with Tcl version 8.6
#    Feb 28, 2018 03:51:08 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import FirstApp_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = My_First_Page_App (root)
    FirstApp_support.init(root, top)
    root.mainloop()

w = None
def create_My_First_Page_App(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = My_First_Page_App (w)
    FirstApp_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_My_First_Page_App():
    global w
    w.destroy()
    w = None


class My_First_Page_App:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("600x450+338+149")
        top.title("My First Page App")
        top.configure(highlightcolor="black")



        self.btnExit = Button(top)
        self.btnExit.place(relx=0.42, rely=0.44, height=24, width=97)
        self.btnExit.configure(activebackground="#d9d9d9")
        self.btnExit.configure(pady="0")
        self.btnExit.configure(text='''Exit''')
        self.btnExit.bind('<Button-1>',lambda e:FirstApp_support.btnExit_LeftClick(e))






if __name__ == '__main__':
    vp_start_gui()



