#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Nov 16, 2017 02:28:08 PM
#    Nov 16, 2017 02:57:57 PM

#======================================================
#    FirstApp_support.py
#------------------------------------------------------
# Created for the Page Tutorial Project
# Written by G.D. Walters
# Copyright (c) 2018 by G.D. Walters
# This source code is released under the MIT License 
# (See MIT_License.txt)
#======================================================

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1




def btnExit_LeftClick(p1):
    print('FirstApp_support.btnExit_LeftClick')
    sys.stdout.flush()
    destroy_window()
    

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import FirstApp
    FirstApp.vp_start_gui()





