#############################################################################
# Generated by PAGE version 4.11f
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

vTcl:font:add_GUI_font font10 \
"-family {DejaVu Sans Mono} -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.fra38
    set site_4_0 $site_3_0.lab44
    set site_4_0 $site_3_0.lab45
    set site_3_0 $base.fra39
    set site_4_0 $site_3_0.scr53

    #Updating ttreeview attributes
    $site_4_0.01 configure\
        -columns  Col1\
        -height  4

    #heading options.
    $site_4_0.01 heading Col1 \
             -text "Col1" \
             -anchor center
    #heading options.
    $site_4_0.01 heading #0 \
             -text "Tree" \
             -anchor center
    #column options.
    $site_4_0.01 column Col1 \
             -width 371 \
             -minwidth 20 \
             -stretch 1 \
             -anchor w
    #column options.
    $site_4_0.01 column #0 \
             -width 370 \
             -minwidth 20 \
             -stretch 1 \
             -anchor w
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 769x541+224+120
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1265 770
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Searcher"
    vTcl:DefineAlias "$top" "searcher" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra38 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 265 \
        -highlightcolor black -width 765 
    vTcl:DefineAlias "$top.fra38" "frameTop" vTcl:WidgetProc "searcher" 1
    set site_3_0 $top.fra38
    label $site_3_0.lab40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Path to search: } 
    vTcl:DefineAlias "$site_3_0.lab40" "Label1" vTcl:WidgetProc "searcher" 1
    entry $site_3_0.ent41 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable FilePath 
    vTcl:DefineAlias "$site_3_0.ent41" "txtPath" vTcl:WidgetProc "searcher" 1
    button $site_3_0.but42 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -command OnBtnSearchPath -foreground {#000000} \
        -highlightcolor black -text ... 
    vTcl:DefineAlias "$site_3_0.but42" "btnSearchPath" vTcl:WidgetProc "searcher" 1
    button $site_3_0.but43 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Exit 
    vTcl:DefineAlias "$site_3_0.but43" "btnExit" vTcl:WidgetProc "searcher" 1
    bind $site_3_0.but43 <Button-1> {
        lambda e: OnBtnExit(e)
    }
    labelframe $site_3_0.lab44 \
        -foreground black -text {Audio Files} -background {#d9d9d9} \
        -height 185 -highlightcolor black -width 250 
    vTcl:DefineAlias "$site_3_0.lab44" "Labelframe1" vTcl:WidgetProc "searcher" 1
    set site_4_0 $site_3_0.lab44
    checkbutton $site_4_0.che47 \
        -activebackground {#d9d9d9} -activeforeground black -anchor w \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text .MP3 -variable VchkMP3 
    vTcl:DefineAlias "$site_4_0.che47" "chkMP3" vTcl:WidgetProc "searcher" 1
    checkbutton $site_4_0.che48 \
        -activebackground {#d9d9d9} -activeforeground black -anchor w \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text .WAV -variable VchkWAV 
    vTcl:DefineAlias "$site_4_0.che48" "chkWAV" vTcl:WidgetProc "searcher" 1
    checkbutton $site_4_0.che49 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text .OGG -variable VchkOGG 
    vTcl:DefineAlias "$site_4_0.che49" "chkOGG" vTcl:WidgetProc "searcher" 1
    place $site_4_0.che47 \
        -in $site_4_0 -x 30 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.che48 \
        -in $site_4_0 -x 30 -y 50 -anchor nw -bordermode ignore 
    place $site_4_0.che49 \
        -in $site_4_0 -x 30 -y 70 -anchor nw -bordermode ignore 
    labelframe $site_3_0.lab45 \
        -foreground black -text {Video Files} -background {#d9d9d9} \
        -height 185 -highlightcolor black -width 270 
    vTcl:DefineAlias "$site_3_0.lab45" "Labelframe2" vTcl:WidgetProc "searcher" 1
    set site_4_0 $site_3_0.lab45
    checkbutton $site_4_0.che50 \
        -activebackground {#d9d9d9} -activeforeground black -anchor w \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text .AVI -variable VchkAVI 
    vTcl:DefineAlias "$site_4_0.che50" "chkAVI" vTcl:WidgetProc "searcher" 1
    checkbutton $site_4_0.che51 \
        -activebackground {#d9d9d9} -activeforeground black -anchor w \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text .MKV -variable VchkMKV 
    vTcl:DefineAlias "$site_4_0.che51" "chkMKV" vTcl:WidgetProc "searcher" 1
    checkbutton $site_4_0.che52 \
        -activebackground {#d9d9d9} -activeforeground black -anchor w \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text .MP4 -variable VchkMP4 
    vTcl:DefineAlias "$site_4_0.che52" "chkMP4" vTcl:WidgetProc "searcher" 1
    place $site_4_0.che50 \
        -in $site_4_0 -x 20 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.che51 \
        -in $site_4_0 -x 20 -y 50 -anchor nw -bordermode ignore 
    place $site_4_0.che52 \
        -in $site_4_0 -x 20 -y 70 -anchor nw -bordermode ignore 
    button $site_3_0.but46 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text GO! 
    vTcl:DefineAlias "$site_3_0.but46" "btnGo" vTcl:WidgetProc "searcher" 1
    bind $site_3_0.but46 <Button-1> {
        lambda e: OnBtnGo(e)
    }
    place $site_3_0.lab40 \
        -in $site_3_0 -x 40 -y 26 -width 99 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent41 \
        -in $site_3_0 -x 140 -y 20 -width 396 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but42 \
        -in $site_3_0 -x 540 -y 22 -width 38 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but43 \
        -in $site_3_0 -x 650 -y 20 -width 79 -relwidth 0 -height 37 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab44 \
        -in $site_3_0 -x 70 -y 60 -width 250 -relwidth 0 -height 185 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 320 -y 60 -width 250 -relwidth 0 -height 185 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but46 \
        -in $site_3_0 -x 600 -y 130 -anchor nw -bordermode ignore 
    frame $top.fra39 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 265 \
        -highlightcolor black -width 761 
    vTcl:DefineAlias "$top.fra39" "frameTreeview" vTcl:WidgetProc "searcher" 1
    set site_3_0 $top.fra39
    ttk::style configure Treeview.Heading -background #d9d9d9
    ttk::style configure Treeview.Heading -font TkDefaultFont
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_3_0.scr53 \
        -background {#d9d9d9} -height 15 -highlightcolor black -width 30 
    vTcl:DefineAlias "$site_3_0.scr53" "Scrolledtreeview1" vTcl:WidgetProc "searcher" 1
    bind $site_3_0.scr53 <Button-1> {
        lambda e: OnTreeviewClick(e)
    }
    place $site_3_0.scr53 \
        -in $site_3_0 -x 4 -y 0 -width 755 -relwidth 0 -height 259 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra38 \
        -in $top -x 4 -y 4 -width 761 -relwidth 0 -height 265 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra39 \
        -in $top -x 4 -y 270 -width 761 -relwidth 0 -height 265 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

