#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.11f
# In conjunction with Tcl version 8.6
#    Feb 28, 2018 04:08:02 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import vlcplayer_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    vlcplayer_support.set_Tk_var()
    top = VLC_Player (root)
    vlcplayer_support.init(root, top)
    root.mainloop()

w = None
def create_VLC_Player(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    vlcplayer_support.set_Tk_var()
    top = VLC_Player (w)
    vlcplayer_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_VLC_Player():
    global w
    w.destroy()
    w = None


class VLC_Player:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {DejaVu Sans} -size -12 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"

        top.geometry("670x500+266+114")
        top.title("VLC Player")
        top.configure(highlightcolor="black")



        self.menubar = Menu(top,font=font9,bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.file = Menu(top,tearoff=0)
        self.menubar.add_cascade(menu=self.file,
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                font="TkMenuFont",
                foreground="#000000",
                label="File")
        self.file.add_command(
                activebackground="#d8d8d8",
                activeforeground="#000000",
                background="#d9d9d9",
                command=vlcplayer_support.mnuFileOpen,
                font="TkMenuFont",
                foreground="#000000",
                label="Open")
        self.file.add_command(
                activebackground="#d8d8d8",
                activeforeground="#000000",
                background="#d9d9d9",
                command=vlcplayer_support.mnuFileExit,
                font="TkMenuFont",
                foreground="#000000",
                label="Exit")
        self.help = Menu(top,tearoff=0)
        self.menubar.add_cascade(menu=self.help,
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                font="TkMenuFont",
                foreground="#000000",
                label="Help")
        self.help.add_command(
                activebackground="#d8d8d8",
                activeforeground="#000000",
                background="#d9d9d9",
                command=vlcplayer_support.mnuHelpAbout,
                font="TkMenuFont",
                foreground="#000000",
                label="About")


        self.frameVideo = Frame(top)
        self.frameVideo.place(relx=0.0, rely=0.0, relheight=0.65, relwidth=0.99)
        self.frameVideo.configure(relief=GROOVE)
        self.frameVideo.configure(borderwidth="2")
        self.frameVideo.configure(relief=GROOVE)
        self.frameVideo.configure(width=665)

        self.Canvas1 = Canvas(self.frameVideo)
        self.Canvas1.place(relx=0.0, rely=0.0, relheight=0.99, relwidth=0.99)
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(relief=RIDGE)
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(width=661)

        self.frameSlider = Frame(top)
        self.frameSlider.place(relx=0.0, rely=0.66, relheight=0.13
                , relwidth=0.99)
        self.frameSlider.configure(relief=GROOVE)
        self.frameSlider.configure(borderwidth="2")
        self.frameSlider.configure(relief=GROOVE)
        self.frameSlider.configure(width=665)

        self.TimeSlider = Scale(self.frameSlider)
        self.TimeSlider.place(relx=0.03, rely=0.15, relwidth=0.76, relheight=0.0
                , height=40)
        self.TimeSlider.configure(activebackground="#d9d9d9")
        self.TimeSlider.configure(command=vlcplayer_support.ScaleSel)
        self.TimeSlider.configure(font="TkTextFont")
        self.TimeSlider.configure(length="500")
        self.TimeSlider.configure(orient="horizontal")
        self.TimeSlider.configure(to="1000.0")
        self.TimeSlider.configure(troughcolor="#d9d9d9")
        self.TimeSlider.configure(variable=vlcplayer_support.ScaleVar)

        self.frameButtons = Frame(top)
        self.frameButtons.place(relx=0.0, rely=0.8, relheight=0.15
                , relwidth=0.99)
        self.frameButtons.configure(relief=GROOVE)
        self.frameButtons.configure(borderwidth="2")
        self.frameButtons.configure(relief=GROOVE)
        self.frameButtons.configure(width=125)

        self.btnPlay = Button(self.frameButtons)
        self.btnPlay.place(relx=0.05, rely=0.27, height=27, width=75)
        self.btnPlay.configure(activebackground="#d9d9d9")
        self.btnPlay.configure(text='''Play''')
        self.btnPlay.bind('<Button-1>',lambda e:vlcplayer_support.OnBtnPlay(e))

        self.btnPause = Button(self.frameButtons)
        self.btnPause.place(relx=0.21, rely=0.27, height=27, width=75)
        self.btnPause.configure(activebackground="#d9d9d9")
        self.btnPause.configure(text='''Pause''')
        self.btnPause.bind('<Button-1>',lambda e:vlcplayer_support.OnBtnPause(e))

        self.btnStop = Button(self.frameButtons)
        self.btnStop.place(relx=0.36, rely=0.27, height=27, width=75)
        self.btnStop.configure(activebackground="#d9d9d9")
        self.btnStop.configure(text='''Stop''')
        self.btnStop.bind('<Button-1>',lambda e:vlcplayer_support.OnBtnStop(e))

        self.btnMute = Button(self.frameButtons)
        self.btnMute.place(relx=0.51, rely=0.27, height=27, width=75)
        self.btnMute.configure(activebackground="#d9d9d9")
        self.btnMute.configure(text='''Mute''')
        self.btnMute.bind('<Button-1>',lambda e:vlcplayer_support.OnBtnMute(e))

        self.VolumeSlider = Scale(self.frameButtons)
        self.VolumeSlider.place(relx=0.71, rely=0.13, relwidth=0.16
                , relheight=0.0, height=40)
        self.VolumeSlider.configure(activebackground="#d9d9d9")
        self.VolumeSlider.configure(command=vlcplayer_support.VolumeSel)
        self.VolumeSlider.configure(font="TkTextFont")
        self.VolumeSlider.configure(orient="horizontal")
        self.VolumeSlider.configure(troughcolor="#d9d9d9")
        self.VolumeSlider.configure(variable=vlcplayer_support.VolumeVar)






if __name__ == '__main__':
    vp_start_gui()



