#############################################################################
# Generated by PAGE version 4.11f
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

vTcl:font:add_GUI_font font10 \
"-family {DejaVu Sans Mono} -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.m38
    set site_3_0 $base.m38
    set site_3_0 $base.fra41
    set site_3_0 $base.fra42
    set site_3_0 $base.fra43
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m38" -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 670x500+266+114
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1265 770
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "VLC Player"
    vTcl:DefineAlias "$top" "vlcplayer" vTcl:Toplevel:WidgetProc "" 1
    set site_3_0 $top.m38
    menu $site_3_0 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    $site_3_0 add cascade \
        -menu "$top.m38.men39" -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label File 
    menu $site_3_0.men39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkMenuFont -foreground black -tearoff 0 
    $site_3_0.men39 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#mnuFileOpen} -font TkMenuFont \
        -foreground {#000000} -label Open 
    $site_3_0.men39 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#mnuFileExit} -font TkMenuFont \
        -foreground {#000000} -label Exit 
    $site_3_0 add cascade \
        -menu "$top.m38.men40" -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label Help 
    menu $site_3_0.men40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkMenuFont -foreground black -tearoff 0 
    $site_3_0.men40 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#mnuHelpAbout} -font TkMenuFont \
        -foreground {#000000} -label About 
    frame $top.fra41 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 325 \
        -highlightcolor black -width 665 
    vTcl:DefineAlias "$top.fra41" "frameVideo" vTcl:WidgetProc "vlcplayer" 1
    set site_3_0 $top.fra41
    canvas $site_3_0.can44 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 321 \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground {#c4c4c4} -selectforeground black -width 661 
    vTcl:DefineAlias "$site_3_0.can44" "Canvas1" vTcl:WidgetProc "vlcplayer" 1
    place $site_3_0.can44 \
        -in $site_3_0 -x 1 -y 1 -width 661 -relwidth 0 -height 321 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra42 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 65 \
        -highlightcolor black -width 665 
    vTcl:DefineAlias "$top.fra42" "frameSlider" vTcl:WidgetProc "vlcplayer" 1
    set site_3_0 $top.fra42
    scale $site_3_0.sca45 \
        -activebackground {#d9d9d9} -background {#d9d9d9} -bigincrement 0.0 \
        -command ScaleSel -font TkTextFont -foreground {#000000} -from 0.0 \
        -highlightcolor black -length 500 -orient horizontal -resolution 1.0 \
        -tickinterval 0.0 -to 1000.0 -troughcolor {#d9d9d9} \
        -variable ScaleVar 
    vTcl:DefineAlias "$site_3_0.sca45" "TimeSlider" vTcl:WidgetProc "vlcplayer" 1
    place $site_3_0.sca45 \
        -in $site_3_0 -x 20 -y 10 -anchor nw -bordermode ignore 
    frame $top.fra43 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 75 \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.fra43" "frameButtons" vTcl:WidgetProc "vlcplayer" 1
    set site_3_0 $top.fra43
    button $site_3_0.but46 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Play 
    vTcl:DefineAlias "$site_3_0.but46" "btnPlay" vTcl:WidgetProc "vlcplayer" 1
    bind $site_3_0.but46 <Button-1> {
        lambda e: OnBtnPlay(e)
    }
    button $site_3_0.but47 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Pause 
    vTcl:DefineAlias "$site_3_0.but47" "btnPause" vTcl:WidgetProc "vlcplayer" 1
    bind $site_3_0.but47 <Button-1> {
        lambda e: OnBtnPause(e)
    }
    button $site_3_0.but48 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Stop 
    vTcl:DefineAlias "$site_3_0.but48" "btnStop" vTcl:WidgetProc "vlcplayer" 1
    bind $site_3_0.but48 <Button-1> {
        lambda e: OnBtnStop(e)
    }
    button $site_3_0.but49 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Mute 
    vTcl:DefineAlias "$site_3_0.but49" "btnMute" vTcl:WidgetProc "vlcplayer" 1
    bind $site_3_0.but49 <Button-1> {
        lambda e: OnBtnMute(e)
    }
    scale $site_3_0.sca50 \
        -activebackground {#d9d9d9} -background {#d9d9d9} -bigincrement 0.0 \
        -command VolumeSel -font TkTextFont -foreground {#000000} -from 0.0 \
        -highlightcolor black -orient horizontal -resolution 1.0 \
        -tickinterval 0.0 -to 100.0 -troughcolor {#d9d9d9} \
        -variable VolumeVar 
    vTcl:DefineAlias "$site_3_0.sca50" "VolumeSlider" vTcl:WidgetProc "vlcplayer" 1
    place $site_3_0.but46 \
        -in $site_3_0 -x 30 -y 20 -width 75 -anchor nw -bordermode ignore 
    place $site_3_0.but47 \
        -in $site_3_0 -x 140 -y 20 -width 75 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 240 -y 20 -width 75 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 340 -y 20 -width 75 -anchor nw -bordermode ignore 
    place $site_3_0.sca50 \
        -in $site_3_0 -x 470 -y 10 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra41 \
        -in $top -x 2 -y 2 -width 665 -relwidth 0 -height 325 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra42 \
        -in $top -x 2 -y 330 -width 665 -relwidth 0 -height 65 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra43 \
        -in $top -x 2 -y 398 -width 665 -height 75 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}
proc ScaleSel {args} { }
proc VolumeSel {args} { }

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

